name: Deploy RankFlow Static Website

on:
  push:
    branches:
      - main  # Triggered when you push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://xsf-0508.github.io/rankflowapi/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Website Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Uploads all files in the root directory (index.html, etc.)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
